### PR TITLE
views: custom view function support

### LINKED ISSUE #5: views/ext: template context processors
It should be possible to add template context processors to the records view in a similar way like flask-security, so that pages such as references/usage statistics etc can ingest custom variables into the template.

### PR DESCRIPTION
**Pull request by lnielsen**
* Adds support for using custom view functions. (closes #5)

Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>

### CODE REVIEW

**Comment by lnielsen** [comment]
@JavierDelgadoFernandez Will you do a code review.

**Comment by JavierDelgadoFernandez** [comment]
@lnielsen For me it looks good.

**Comment by JavierDelgadoFernandez** [comment]
@lnielsen :shipit:

**Comment by lnielsen** [comment]
Ready

**Pull request merged**
